### ISSUE TITLE
Week number isn't updated

### ISSUE THREAD

**Issue by pederalm** [voltura/WeekNumberLite2#1]
If I keep my computer on during the night the week number isn't updated if a new week has started. There seams to be some issue with the date update trigger. The image below show an example where the application is two days behind.

![image](https://user-images.githubusercontent.com/39690274/214782224-fa2d41f5-36d4-404d-b43e-4d9d85c14631.png)

**Comment by voltura** [comment]
Hi, thanks for using the app. I have released a new version that should rectify the issue. Now the app checks if new week has occurred every 10 seconds. Prior this check interval was computed, this computation might have been invalid. Please try this version out: https://github.com/voltura/WeekNumberLite2/releases/tag/v1.0.0.6
